USE QLBH;

-- PHAN 1
-- BAI 2
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20);
-- BAI 3
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT;
-- BAI 4
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);
-- BAI 5
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;
-- BAI 6
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20);
-- BAI 7
ALTER TABLE SANPHAM
ADD CONSTRAINT CHK_DVT CHECK (DVT IN ('cay','hop','cai','quyen','chuc'));
-- BAI 8
ALTER TABLE SANPHAM
ADD CONSTRAINT CHK_GIA CHECK (GIA >= 500);
-- BAI 9
ALTER TABLE CTHD
ADD CONSTRAINT CHK_SL CHECK (SL >= 1);
-- BAI 10
ALTER TABLE KHACHHANG
ADD CONSTRAINT CHK_NGDK CHECK(NGDK > NGSINH);

-- PHAN 2
-- BAI 2
SELECT * INTO SANPHAM1 FROM SANPHAM;
SELECT * INTO KHACHHANG1 FROM KHACHHANG;
-- BAI 3
UPDATE SANPHAM1
SET GIA = GIA * 105 /100
WHERE NUOCSX = 'THAILAN';
-- BAI 4
UPDATE SANPHAM1
SET GIA = GIA * 95/100
WHERE NUOCSX = 'TRUNGQUOC' AND GIA < 10000;
-- BAI 5
SET DATEFORMAT DMY 
UPDATE KHACHHANG1
SET LOAIKH='VIP'
WHERE NGDK< '1-1-2007' AND DOANHSO >10000000 OR NGDK >= '1-1-2007' AND DOANHSO > 2000000
SELECT * FROM SANPHAM1;

-- PHAN 3
-- BAI 1
SELECT MASP, TENSP FROM SANPHAM WHERE NUOCSX='TRUNGQUOC'
-- BAI 2
SELECT MASP, TENSP FROM SANPHAM WHERE DVT='CAY' OR DVT='QUYEN'
-- BAI 3
SELECT MASP, TENSP FROM SANPHAM WHERE MASP LIKE 'B%01' 
-- BAI 4
SELECT MASP, TENSP FROM SANPHAM WHERE NUOCSX='TRUNGQUOC' AND GIA >=30000 AND GIA <= 40000
-- BAI 5
SELECT MASP, TENSP FROM SANPHAM WHERE (NUOCSX='TRUNGQUOC' OR NUOCSX = 'THAILAN') AND GIA >=30000 AND GIA <= 40000
-- BAI 6
SELECT SOHD, TRIGIA FROM HOADON WHERE NGHD = '1-1-2007' OR NGHD = '2-1-2007'
-- BAI 7
SELECT SOHD, TRIGIA FROM HOADON WHERE (MONTH(NGHD) = 1 AND YEAR(NGHD) = 2007) ORDER BY TRIGIA DESC
-- BAI 8
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN, HOADON.NGHD
FROM KHACHHANG INNER JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
WHERE HOADON.NGHD = '1-1-2007'
-- BAI 9
SELECT HOADON.SOHD, HOADON.TRIGIA
FROM HOADON INNER JOIN NHANVIEN ON NHANVIEN.MANV = HOADON.MANV
WHERE HOADON.NGHD = '28-10-2006' AND NHANVIEN.HOTEN = 'NGUYEN VAN B'
-- BAI 10

-- BAI 11
SELECT SOHD FROM CTHD WHERE MASP IN ('BB01', 'BB02')
-- BAI 12
SELECT SOHD FROM CTHD WHERE MASP IN ('BB01', 'BB02') AND SL BETWEEN 10 AND 20
-- BAI 13
SELECT SOHD FROM CTHD WHERE MASP = 'BB01' AND SL BETWEEN 10 AND 20
INTERSECT
SELECT SOHD FROM CTHD WHERE MASP = 'BB02' AND SL BETWEEN 10 AND 20
-- BAI 14
SELECT MASP, TENSP FROM SANPHAM WHERE NUOCSX='TRUNGQUOC'
UNION
SELECT SANPHAM.MASP,TENSP FROM SANPHAM, HOADON, CTHD WHERE SANPHAM.MASP = CTHD.MASP AND CTHD.SOHD = HOADON.SOHD  AND NGHD='1-1-2007';
-- BAI 15
SELECT MASP, TENSP FROM SANPHAM
EXCEPT
SELECT SANPHAM.MASP, TENSP FROM SANPHAM, CTHD WHERE SANPHAM.MASP = CTHD.MASP
-- BAI 16
SELECT MASP, TENSP FROM SANPHAM
EXCEPT
SELECT SANPHAM.MASP, TENSP FROM SANPHAM, CTHD, HOADON WHERE SANPHAM.MASP = CTHD.MASP AND CTHD.SOHD = HOADON.SOHD 
															AND YEAR(HOADON.NGHD)= 2006
-- BAI 17
SELECT MASP, TENSP FROM SANPHAM WHERE NUOCSX = 'TRUNGQUOC'
EXCEPT
SELECT SANPHAM.MASP, TENSP FROM SANPHAM, CTHD, HOADON WHERE SANPHAM.MASP = CTHD.MASP AND CTHD.SOHD = HOADON.SOHD 
															AND YEAR(HOADON.NGHD)= 2006 AND NUOCSX = 'TRUNGQUOC'
